### ISSUE TITLE
StringView/File/Utils.hpp Segmentation Fault

### ISSUE THREAD

**Issue by LeslieM98** [Lehks/NostraUtils#38]
Take a look at the unittests in b95d700aa83608fe247433c19cdd810d449d19ea
in line 1903.
Methodcalltrace leads into StringView.hpp(line 880) then Utils.hpp(line 111) then Utils.hpp which somehow causes a Segmentation fault.
This error only occurs on Linux fedora currently. Try a debugger and allwas hit "Step into".
Easily reproducable by just executing the UnitTests and also making sure the UnitTestFile File will be deleted before every run since this error prevents it from being deleted.

**Comment by xC0rp** [comment]
Issue was caused by naming the static memberfunction fopen, which caused some incorrect linking.
Also the signature of fopen() in line 14 was incorrectly and went unnoticed due to the incorrect linking earlier.

The fopen call has been set accordingly, the static member function has been renamed and all corresponding membercalls have been changed accordingly.
